---
title: "미국 아카데믹 잡마켓 준비"
author: 
  name: "김재연"
  url: https://jaeyk.github.io
format:
  html:
    theme: cosmo
    css: styles.css
date: today
---

미국 아카데믹 잡 마켓 준비에 대한 조언을 적어 봅니다.각자의 상황이 다르기 때문에 아래의 조언은 그 한계를 고려하여 적절하게 수용하고 적용하시길 추천합니다.

## 왜 잡마켓은 힘든가?

아카데믹 잡 마켓이 힘든 가장 근본적 이유는 잡은 적고, 잘 하는 사람은 많기 때문입니다. 부가적인 이유는 많은 지원자들이 “연구를 잘 하는 것”과 “잡을 얻는 것”이 완벽하게 상관되어 있다고 믿기 때문입니다. 당연히 둘은 양의 상관관계가 있으나 그 상관계수는 1이 아닙니다.

연구를 잘 하는 것은 필요 조건이지만 충분 조건은 아닙니다. 내가 잘 하는 만큼이 아니라, 내가 (1) “잘 하는 것”, (2) “잘 할 것”을, (3) “잘 커뮤니케이션”한 만큼 좋은 인상을 줍니다. 그 인상을 바탕으로 서치 커미티가 이 지원자가 “잘 하고, 잘 할 것이고, 핏이 맞는다”라고 인식한 만큼 잡 오퍼를 받을 확률이 높아집니다. 춤은 두 사람이 같이 춰야 합니다.

이 커뮤니케이션 목표를 바쁘고 귀찮은 사람들(=서치 커미티)을 대상으로 달성하는 것은 어렵습니다. 그래서 잡 마켓은 어렵고, 많은 준비와 노력, 연습이 필요합니다.

나아가, 대학에서 교원 채용을 위한 “서치”가 어떻게 이뤄지는지를 생각해 볼 필요가 있습니다. 서치 커미티에 들어오는 교수들은 꼭 그 해 라인이 나온 분야에서 학과 내 가장 적절한 전문가들만은 아닙니다. 그런 분들도 있지만, 어쩌다 그 해 그 서비스를 해야 해서 참여하게 된 분들도 있습니다. 특정 서치가 공고되어 나오는 것은 결국 학과와 행정 간의 협상 결과입니다. 따라서 공고문에 있는 내용을 실제 학과의 수요로 문자 그대로 해석하는 것은 무리가 있습니다. 상대방의 필요를 파악해야 어떻게 커뮤니케이션할지 전략을 세울 수 있는데, 그 탐색 과정에서도 이미 많은 노이즈와 부정확한 시그널을 마주치게 됩니다.

위와 같은 제약 조건 하에서 서치 커미티에게 “내가 학과가 원하는 올해 최고의 지원자”임을 커뮤니케이션하기 위해, 제 의견에 따라 생각해 볼 만한 지점들을 아래 세 가지로 정리해 보았습니다.

## 1. “Who am I?” (One-liner)

서치 커미티들은 기본적으로 매우 바쁩니다. 자기 연구도 하고, 수업도 가르치며, 학생 지도까지 해야 하는 와중에 서치 커미티에 참여해야 하기 때문입니다. 경쟁력 있는 학과라면 한 라인에 지원자가 수백 명이 넘습니다. 서치 커미티는 그 많은 지원자들 중에서 롱리스트와 숏리스트를 만들고, 줌 인터뷰를 진행하며, 지원자가 캠퍼스 인터뷰에 올 경우 잡 톡을 포함한 여러 번의 미팅과 때로는 식사까지 진행합니다.

이 바쁘고 귀찮은 사람들을 위해 나는 “어떤 학자다”라는 것을 단 한 문장(one-liner)으로 정리해 설명할 수 있어야 합니다. 이 내용은 잡 마켓 패킷(커버 레터 등), 개인 홈페이지, 잡 톡, 그리고 패컬티와 1:1 미팅 시 모두 일관되게 언급되어야 합니다. 그렇게 해야 서치 커미티와 학과 교수들이 “특정 분야를 연구하는 사람이다”라는 인상을 머릿속에 남길 수 있습니다. 남이 나를 정의하기 전에, 내가 나를 정의하는 것은 대화의 우선권을 잡기 위한 중요한 전략입니다.

다만, 학과도 다양하고 특정 채용 공고가 나오는 이유도 다르므로, 내가 “어떤 학자다”라고 어필하는 방식은 그 맥락에 따라 달라져야 합니다. 저는 2024년 아카데믹 잡 마켓에서 정책과 데이터 과학 잡에 모두 지원했는데, 정책학 인터뷰에서는 어떤 분야의 정책을 연구하는지를, 데이터 과학 인터뷰에서는 어떤 분야의 데이터 과학을 연구하는지를 각각 어필했습니다.

여기서 중요한 것은 서치 커미티가 “내가 어떤 분야를 연구하는 학자”라는 이야기를 들었을 때, “이 분이 우리 학과에서 필요한 학자”라는 인식을 가져야 한다는 점입니다.

달리 말하면, 서치 커미티가 “어떤 분야를 연구하는 학자이십니까?”라고 질문할 때, 그 기저에는 “우리가 뽑으려는 분야의 학자이십니까?”라는 질문이 숨어 있습니다. 이 차이를 염두에 두어야 합니다.

## 2. “Who am I becoming?” (2–3 sentences)

잡 마켓에 나오기 전까지 지난 시간 동안 많은 노력과 수고를 했을 것입니다. 그러나 학과가 교원을 채용할 때는 그 사람의 과거를 보고 인터뷰에 초청하지만, 그 사람의 미래를 보고 오퍼를 제공합니다. 오퍼는 투자입니다. 따라서 나의 과거와 현재뿐만 아니라, 나의 미래와 잠재성을 설명하는 것이 매우 중요합니다. 그래서 줌 인터뷰에서 거의 반드시 나오는 질문 중 하나가 향후 3–5년 동안 어떤 연구를 할 것인지에 관한 것입니다.

Who am I becoming?”에 답하는 원칙도 “Who am I?”에 답하는 원칙과 비슷합니다. 앞에서는 한 문장을 통해 “내가 어떤 분야를 연구하는 학자다”를 강조했다면, 여기서는 2–3 문장을 통해 내가 “어떤 분야에서 유망할 학자다”라는 점을 강조해야 합니다.

이 포인트가 중요한 이유는 여러 가지가 있습니다.

첫 번째, 전임 트랙에서 교원을 뽑을 경우 이 사람이 몇 년 후 테뉴어를 받을 수 있을 것을 전제로 합니다. 미국의 연구 중심 대학에서 테뉴어를 받으려면 그 분야에서 유망한 학자가 되어야 합니다. 학과는 지원자가 지금까지 잘한 것 때문에 잡 인터뷰 요청을 하지만, 테뉴어 트랙 지원자를 대상으로 인터뷰할 때는 이 사람이 테뉴어를 받을 수 있을지 판단해야 합니다. 이때 후속 연구, 즉 리서치 파이프라인의 가능성과 잠재적 임팩트를 보여주는 것이 중요합니다.

두 번째, 지금까지 연구한 분야가 채용 공고의 핏과 잘 맞지 않더라도, 앞으로 연구할 분야가 채용 공고의 핏과 어떻게 맞는지 설명할 수 있습니다. 따라서 이 질문은 내 핏을 한 번 더 설명할 수 있는 매우 좋은 기회입니다.

## 3. “What is my fit?” (1–2 good questions)

인터뷰 과정에서는 반드시 서치 커미티에게 질문할 기회가 주어집니다. 줌 인터뷰에서나 캠퍼스 인터뷰에서나, 혹은 평소 대화 중에도 상대방의 질문을 통해 그 사람이 얼마나 대화에 집중하고 있으며 나에게 관심이 있는지 알 수 있습니다. 이 질문 기회는 내가 학과에 얼마나 관심이 있는지를 보여줄 수 있는 좋은 기회입니다.

저는 거의 모든 줌 인터뷰에서 학과가 어떤 학자를 뽑으려 하는지에 대해 서치 커미티에게 물었습니다. 보통 이 시점이면 제 연구 분야, 앞으로 연구할 분야, 가르칠 과목, 학생 지도 방법 등을 설명한 후입니다. 이때 서치 커미티가 본인들 입장에서 핏을 설명하는데, 내가 설명한 핏과 맞지 않다면 내 노력이 실패한 것이고, 맞다면 내가 잘한 부분이 있는 것입니다. 놓친 부분이 있다면 향후 수정해야 합니다.

위의 질문을 제외하면, 줌 인터뷰나 캠퍼스 인터뷰에서 나머지 질문들은 서치 커미티가 (1) 적극적이고 (2) 긍정적으로 대답할 수 있는 질문 위주로 진행됩니다. **서치 커미티는 지원자가 어떤 질문을 했는지보다, 그 질문에 대해 대답했을 때 어떤 기분을 느꼈는지를 기억합니다.** 그래서 상대방의 입장에서 어떤 질문을 할지 신중하게 생각하는 것이 필요합니다. 예를 들어, 학제간 연구가 활발한 학과라면 학제간 연구 지원에 관한 구체적인 질문을 하는 것이 좋습니다. 이러한 내용은 학과 홈페이지나 서치 커미티에 속한 교수들의 홈페이지에서 쉽게 확인할 수 있으며, 학제간 연구가 활발하지 않은 학과라면 이러한 질문은 피하는 것이 좋습니다.

내가 질문할 기회가 주어졌을 때는, 내가 그 학과에 얼마나 관심이 있는지를 보여줄 수 있는 좋은 기회입니다. “더 질문할 것이 있냐?”는 질문은 “너가 우리에게 얼마나 관심 있니? 우리를 잘 이해하고 있니?”라는 질문과도 같습니다.

## 마무리: 잡마켓 준비는 재즈처럼

대화의 상대방에 따라 대화의 방향과 방식은 달라질 수밖에 없습니다. 잡 마켓에 나오면 경쟁이 치열하기 때문에 여러 학교와 학과에 지원해야 합니다. 이렇게 많은 학교와 학과에 대해 맞춤형 커뮤니케이션을 준비하다 보면 상당한 시간, 노력, 연습이 필요합니다.

여기서 중요한 것은 내가 어떤 질문에 어떻게 답변할지를 미리 준비해보되, 그 대본 그대로 따라가기보다는 유연하게 대응하는 것입니다. 내가 예상한 대로 상황이 전개되는 경우는 드물기 때문입니다. 따라서 잡 마켓에서 해야 할 커뮤니케이션은 고전 음악보다는 재즈 음악을 연주하는 것과 비슷합니다. 주어진 상황에서 어떤 말을 어떻게 할 것인지에 대한 기본적인 전략은 필요하지만, 응용력이 더욱 중요합니다. 

부단한 노력에도 불구하고 잡 마켓은 근본적으로 만만하지 않기 때문에 많은 불확실성을 견뎌내야 하고, 거절을 경험해야 합니다. 그 와중에 노이즈도 있지만 유용한 데이터 포인트도 있으니, 이를 잘 구분하시길 추천합니다.

우리는 기계가 아니라 사람이기에 잡 마켓 탐색 과정에서 스트레스가 심하고, 그로 인해 정신 건강에 악영향을 받을 수 있습니다. 장기전을 위해 스트레스를 잘 관리하는 습관을 만드는 것이 중요합니다. 건강하게 식사하고, 숙면을 취하며, 정기적으로 운동하고, 무엇보다 서포트 그룹을 통해 필요한 정서적 위로, 지속적 지지, 전략적 조언을 받으시길 추천합니다. 그 어느 때보다 Lean On(린 온)할 때입니다.