---
title: "미국 아카데믹 잡톡 준비"
author: 
  name: "김재연"
  url: https://jaeyk.github.io
format:
  html:
    theme: cosmo
    css: styles.css
date: today
---

이 장에서는 아카데믹 잡톡에 대한 조언을 정리해 보았습니다.

캠퍼스 방문을 준비하는 들에게 도움이 되기를 바랍니다.

## 1. It’s not about YOU (잡톡에서 가장 중요한 건 내가 아닙니다).

모든 사람들에게 상대적으로 자신감이 떨어지는 부분들이 있습니다. 예를 들어, 모국어가 영어가 아니라서 영어로 발표하는 것에 부담을 느끼면 잡톡에서도 그 부분에 가장 많은 신경을 쓰기가 쉽습니다.

그러나 내가 걱정하는 것과 상대방이 원하는 것이 반드시 일치하지 않습니다. 둘 사이에서 잡톡을 준비할 때 우선순위를 두어야 한다면 “상대방이 원하는 것”이 “내가 걱정하는 것”보다 우선되어야 합니다. 누군가에게 내가 원하는 것(이 경우 잡 오퍼)을 받고자 한다면 “그 사람이 원하는 것”에 신경 써야 합니다. 내가 걱정하는 것은 보통 나만 크게 걱정하는 경우가 많습니다.

학과에서 테뉴어 트랙 지원자에게 기대하는 바는

-   "이 사람이 잘 하느냐”
-   "앞으로 가능성이 있느냐”
-   “이번에 우리가 원하는 라인과 핏이 맞느냐”
-   “학과의 다른 패컬티와 잘 지낼 것 같으냐”
-   “학생들에게 도움이 될 것 같으냐”

등일 것입니다. 좋은 잡톡은 이러한 “질문에 답하고 기대에 부응하는 잡톡”입니다.

어떤 패컬티들은 서치 커미티에 참여하거나 1:1 그룹 미팅에서 지원자를 만나보고 대화도 하겠지만, 나머지 패컬티들은 잡톡을 실황이나 녹화로 보고, 그 내용만 가지고 지원자를 판단합니다. 서치 커미티가 지원자를 순위를 매겨 추천하더라도, 이들을 포함한 패컬티 투표가 결과에 영향을 미치므로 잡톡에 신경 써야 합니다.

잡톡을 정말 잘 한다고 해서 애초에 핏이 맞지 않는 포지션에서 오퍼를 받기는 어렵습니다. 그러나 잡톡을 정말 잘 못한다면, 핏이 잘 맞는 포지션에서도 오퍼를 받기 쉽지 않습니다.

이상적인 잡톡은 투표권을 가진 패컬티가 호기심을 가지고 잡톡에 참여하여, 적어도 지원자에 대한 호감과 매력을 느끼고 나오는 것입니다. 이들 패컬티 중 많은 수는 바쁘고, 잡톡에 참여하거나 확인하는 것을 귀찮아하며, 내 연구와 무관한 분야를 연구하거나 평소에 이 주제에 대해 생각해 본 적이 없는 경우가 많습니다.

그래서 많은 지원자들이 자기 연구와 업적을 설명하는 데 바쁘지만, 그와 함께 본인 연구의 중요성, 맥락, 방향성을 설명하는 것(so what)도 굉장히 중요합니다. 바쁘고 귀찮고 무관심한 패컬티들이 잡톡에서 한 가지만 배워간다면, 그 메시지는 무엇일까요? 그 메시지를 어떻게 하면 가장 전략적이고 효과적으로 전달할 수 있을까요?

## 2. Repeat the ONE message (하나의 메시지를 반복하세요)

잡톡에서 중요한 메시지를 정했다면, 그 메시지는 반복해야 합니다. 나는 내 연구에 지난 수년을 투자했고, 이 잡톡에 내 커리어가 걸려 있기 때문에 잡톡이 정말 중요하겠지만, 잡톡에 참여하는 사람들의 입장에서는 단지 연례행사에 불과할 수 있습니다. 늦게 들어오는 사람들도 있고, 듣다가 딴 생각하는 사람들도 있으며, 스마트폰으로 이메일을 체크하는 사람들도 있겠죠. 청중이 내가 하는 것처럼 잡톡 내내 엄청 집중하고 있다고 가정하면 위험합니다.

그래서 (페이퍼와 마찬가지로) 잡톡에서 중요한 메시지는 하나여야 하며, 그 하나의 메시지는 반복해야 합니다. 어차피 대부분의 청중은 잡톡에서 하나 이상의 메시지를 기억하지 못합니다.

## 3. SHOW, don’t tell (말하지 말고 보여주세요)

슬라이드 덱을 준비할 때, 이미지로 보여줄 수 있는 것이 있다면 글자 대신 이미지로 보여주세요.

글자를 써야 한다면, 쓸 수 있는 가장 큰 글씨를 사용하세요. 글씨가 작으면 집중력이 떨어집니다. 눈이 안 좋은 패컬티가 강의실 끝에 앉아 슬라이드를 대충 봐도 쉽게 읽을 수 있을 만큼 글자가 커야 합니다.

써야 할 글자 수를 최대한 줄이세요. 화면에 글자가 많으면 집중력이 떨어집니다. 전 슬라이드에서 Figure 1,2,3, Table 1,2,3 등의 사소한 글자들도 모두 지웠습니다.

지원하신 분야와 학과에 따라 다르겠지만, 보통 잡톡에 주어진 시간은 한 시간에서 한 시간 반입니다. 여기에 질의응답 시간도 포함되어 있으니, 실제 주어진 시간은 그보다 훨씬 짧습니다. 전달할 내용이 많아질수록 마음이 급해지고, 마음이 급해지면 잡톡을 잘하기 어렵습니다.

잡톡을 망치는 지름길은 슬라이드를 읽는 것입니다. (제가 잡톡을 듣는 입장에서, 지원자가 슬라이드를 읽는다는 느낌을 받으면 잡톡에 대한 기대 수준이 굉장히 낮아집니다. 한 번 이런 첫인상을 주면 바꾸기 어렵습니다.) 슬라이드는 내가 대본을 읽기 위해 존재하는 것이 아니라, 말로 설명하기 어려운 부분이나 강조하고 싶은 부분을 “보여주기” 위해 존재합니다. 읽지 말고 보여주세요.

## 4. Practice until YOU CAN’T GET IT WRONG (실패하기 어려울 때까지 연습하세요)

잡톡을 준비할 때, 슬라이드 덱과 대본을 준비하는 것은 오직 첫 단계일 뿐입니다.

플라이아웃하기 전에 적어도 세 번은 프랙티스 잡톡을 해보길 추천합니다. 이 프랙티스 잡톡들 사이에 약간의 간격을 두어, 첫 번째 프랙티스 잡톡에서 지적받은 부분들은 두 번째에서, 두 번째에서 지적받은 부분들은 세 번째에서 개선하길 바랍니다.

가급적, 이 세 번의 잡톡은 다른 청중을 대상으로 진행해 보세요. 사람마다 같은 잡톡에서도 다른 부분의 문제가 보일 수 있기 때문입니다.

프랙티스 잡톡을 시작하기 전에, 미리 어떤 종류의 피드백이 필요한지와 그것을 어떻게 받을 것인지 알려주세요.

-   온라인으로 프랙티스 잡톡을 진행하는 경우, 잡톡을 녹화하여 도중에 나온 질문을 문서로 정리할 수 있습니다.

-   개인 사정상 프랙티스 잡톡에 참여 못하는 어드바이저, 동료, 지인이 있다면 녹화된 동영상을 공유해 그 방법으로 피드백을 받을 수 있습니다.

피드백을 받는 채널은 다양한 것이 좋습니다. 사람마다 선호가 다르기 때문입니다. 이메일로 피드백을 주길 원하는 사람들에게는 이메일로, 구글 문서와 같은 공개 도구를 선호하는 사람들에게는 그 방식으로 받기를 추천합니다 (제가 선호하는 방식입니다).

이 톡을 할 수 있겠다 (practice until you get it right)가 아니라, 아주 최악의 상황이 발생하지 않는 한 이 톡을 정말 잘 할 수 있겠다 (practice until you can’t get it wrong)는 자신감이 올 때까지 연습하는 것을 추천합니다.

제 경우, 이 시점은 머릿속에 (1) 잡톡에 대한 하나의 중요한 메시지가 있고, (2) 전반적인 내러티브가 있으며, (3) 각 장표 간의 흐름을 이해하고 있고, (4) 예상되는 질문들을 알고 있으며, (5) 그 질문들 중 어떤 내용을 실제 잡톡에서, 어떤 내용을 질의응답 시간에 어떻게 대응할 것인지에 대한 준비가 충분히 된 상태입니다.

예상되는 모든 질문을 실제 잡톡에서 다 다룰 필요는 없습니다.

-   일부 예상 질문은 질의응답 시간에 받아, 내가 원하는 방향과 페이스로 끌고 갈 수 있습니다. 질의응답 능력도 패컬티가 관심 있게 보는 영역입니다. 이러한 경우, 관련 질문에 대한 슬라이드를 어펜딕스에 넣어두는 것이 좋습니다. 청중은 그 자리에서 답을 듣는 것 같지만, 사실 그 질문에 대한 답뿐 아니라 그 질문이 나오는 것도 어느 정도 미리 준비한 상태여야 합니다.

-   이 정도로 준비를 했다면, 호스트가 잡톡 도중에 사람들이 끼어드는 것을 허락할 것인지, 아니면 잡톡이 끝나길 기다렸다가 질문하도록 할 것인지를 물을 때, 끼어드는 것을 허락하는 것이 좋습니다.

-   청중이 잡톡에서 배운 것 못지 않게 발표자에 대한 “느낌”도 굉장히 중요합니다. 노력하고 준비한 만큼 자신감을 보여주세요.

## 5. Anxiety is your friend until it becomes toxic (긴장이 꼭 나쁜 것은 아닙니다).

긴장은 독소가 되기 전까지는 우리의 친구입니다. 긴장감이 들기 시작하면, 내 몸과 마음이 실전에 대응하기 위한 준비 상태에 있다고 판단할 수 있습니다. 다만, 이 상태가 너무 심해지면 최선의 퍼포먼스를 내기 어렵기 때문에, 본인에게 맞는 몇 가지 대응 방식을 미리 준비하고 연습해 두면 좋습니다. 무엇이 좋은 긴장 대응 방식인지는 개인마다 다를 것입니다.

발표 전에…

-   저는 심호흡을 합니다.

-   숫자를 거꾸로 셉니다. 10, 9, 8…

-   따뜻한 물이나 차를 텀블러에 담아(컵은 흘릴 수 있으므로) 발표할 때 옆에 준비해 둡니다. 실제로 마시거나, 긴장감이 느껴지면 마시는 척하고 잠깐 숨을 돌려도 좋습니다.

-   발표 전에 기술적 문제가 발생하면 긴장이 증가합니다. 그래서 저는 이메일, 랩탑, USB 드라이브 모두에 발표 슬라이드를 저장합니다.

-   옷(남성의 경우 슈트)은 여벌을 준비합니다. 한 벌이 더러워지면 다른 벌로 대체할 수 있도록 해두면 좋습니다.

-   포인트는 긴장은 자연스러운 것이나, 과도해지면 해롭기 때문에 긴장을 약간 낮추는 본인만의 방법을 만들어 두는 것입니다.

-   돌발 상황은 긴장을 높이므로, 이에 대해 예측하고 대비하시기를 추천합니다.
