---
title: "미국 테뉴어 트랙 잡 오퍼 협상"
author: 
  name: "김재연"
  url: https://jaeyk.github.io
format:
  html:
    theme: cosmo
    css: styles.css
date: today
---

먼저 테뉴어 트랙 잡 오퍼를 받으신 것을 축하합니다.

이 장에서는 미국 대학에서 테뉴어 트랙 잡 오퍼를 받고 협상할 때 고려할 포인트를 정리해 보았습니다.

## 1. 체어로부터 오퍼를 받았습니다. 협상을 해야 할까요?

미국 대학에서 테뉴어 트랙 오퍼를 받으면, 협상은 통념적으로 기대되는 절차입니다.

협상의 목표는 지원자가 테뉴어 트랙에서 성공하기 위해 지원자와 학과가 모두 윈-윈하는 환경을 만드는 데 있습니다. 협상을 하는 것이 결과적으로 양쪽 모두에게 좋은 일입니다. 연구 환경이 개선되어 지원자가 연구를 더 잘하게 된다면, 해당 지원자가 테뉴어를 받을 가능성이 높아지겠죠. 학과가 지원자가 제공하는 가치에 걸맞은 대가를 지불하고, 지원자의 우선순위를 이해한다는 인상을 준다면, 해당 지원자의 리텐션 가능성이 높아집니다. 테뉴어 트랙 후보자를 검증하고 선발하는 데에는 많은 비용이 들며, 비슷한 라인이 이후에 나올 수도 있는 상황입니다. 지원자가 테뉴어를 받고 리텐션되는 것은 지원자와 학과 모두에게 중요하고 가치 있는 목표입니다.

또한, 협상을 해야 하는 중요한 현실적 이유는 학과가 제시하는 이니셜 오퍼가 최선의 오퍼가 아닌 경우가 많기 때문입니다. 지원자가 협상을 하지 않을 것을 염두에 두고(잡 마켓 경험이 적거나 아웃사이드 오퍼가 없거나 리텐션 오퍼를 받을 상황이 아니라서), 학과에서 줄 수 있는 것보다 낮춰서 제시하는 경우가 많습니다. 혹은 체어가 더 줄 수 있다는 점을 인지하지 못했다가, 협상 과정에서 깨닫는 경우도 있습니다. 체어가 안 된다고 생각했는데, 협상할 때 딘에게 얘기해 보니 딘이 된다고 해서 되는 경우도 있죠.

마지막으로, 협상을 해야 하는 중요한 이유는 체어와 여러 조건에 대해 이야기하다 보면, 캠퍼스 비짓시 알지 못했던 학교와 학과의 다양한 사정(어떤 부분에 내가 생각한 것보다 자원이 더 많다든지, 어떤 부분에 더 제약이 많다든지)을 이해하게 되기 때문입니다. 이는 협상한 조건이 내가 생각한 유리한 방향으로 흘러가든 그렇지 않든, 알아두면 유용한 정보입니다.

이니셜 오퍼는 체어가 전화로 해주는 경우가 많은데, 이때 바로 승낙할 필요는 없습니다. “고맙다”, “너의 동료가 될 가능성에 기대된다” 등의 통상적인 답례를 하고, 대신 구체적인 조건들은 서면으로 받은 뒤 종합적으로 검토해 회신하면 됩니다. 오퍼를 받은 당시에 결정하지 않아도 체어는 충분히 이해합니다. 제 경우는 고려 사항이 많아 오퍼를 받고 한 달 가까이 협상을 했습니다. 일반적으로, 학과에서 오퍼를 준 지원자에게 적어도 1\~2주는 협상할 시간을 줍니다.

## 2. 협상은 종합적으로 하시길 추천합니다.

체어에게 전화로 “축하한다”와 함께 “너에게 오퍼를 준다”는 전화 통보를 받고 당일, 혹은 늦어도 1\~2일 내로 구체적인 조건을 적은 이메일이 옵니다.

버발로 오퍼를 받은 자리에서 승낙하는 것은 당연히 좋지 않으며, 서면 오퍼를 받은 후에도 조건을 하나씩 나눠서 협상하는 것은 좋지 않습니다.

협상은 충분한 정보를 수집한 후 종합적으로 진행하시길 추천합니다. 예를 들어, 학과가 서면 오퍼를 받고 승낙하기까지 2주의 시간을 준다고 가정합시다. 사실, 이 데드라인도 보통 소프트 데드라인인 경우가 많아 약간 연장이 가능합니다. 시간이 부족하다고 느끼시면, 이건 중요한 결정이므로 가족과 상의해야 해서 조금만 더 시간을 달라고 말씀하셔도 됩니다.

그 주어진 시간 내에 서치 커미티나 캠퍼스 비짓 시 만났던 특히 쥬니어 패컬티들에게 연락하여, 우선 “좋게 봐줘서 감사하다”고 이야기한 후, 오퍼에 대해 흥미는 있으나 최근 오퍼를 받은 사람들이 협상을 했는지, 어떤 부분에서 협상을 했는지 물어보세요. 거기서 어떻게, 얼마나 협상할 수 있는지에 대한 기본적인 정보를 얻을 수 있습니다. 일반적으로 지속적으로 제공되는 조건(샐러리)은 까다롭게 협상되는 경우가 많고, 일시적으로 제공되는 조건(1\~2년 티칭 로드를 줄인다든지, 무빙 익스펜스를 늘린다든지) 등에 대해서는 좀 더 유연한 경우가 많습니다. 종합적으로 여러 조건을 고려할 때, 어떤 조건이 나(와 내게 소중한 사람들)에게 더 중요한지 그 우선순위를 결정하시길 바랍니다.

이렇게 정보 수집 후 종합적으로 협상하는 것이 중요한 이유는 제가 볼 때 세 가지가 있습니다.

1.  이 과정에서 학과와 지원자 모두 서로 어디에 제약이 있는지, 우선순위가 무엇인지를 알게 됩니다. 이것 자체가 매우 유용합니다.

2.  트레이드가 가능해집니다. 학과에게는 양보할 수 없는 조건이 지원자에게는 양보할 수 있는 조건인 경우가 있습니다. 트레이드가 쉬워지므로 패키지로 딜을 하는 것이 좋습니다.

3.  나눠서 협상하면 협상 기간이 길어지고 양쪽 모두 피곤해집니다. 어차피 나중에 같이 일할 사람들이니 굳이 피곤한 상황을 만들 필요는 없습니다.

## 3. 협상의 시작은 ‘거절’을 받는 것입니다

“학과가 나를 원하는 만큼”, “내 가치를 인정해 주는 만큼” 나에게 바게닝 파워가 있습니다. 그래서 한 학과로부터 오퍼를 받았는데, 아직 인터뷰 일정이 있는 다른 학과가 있다면 가장 먼저 할 일은 그 다른 학과에 연락하여 다음 인터뷰 일정을 앞당기는 것입니다. 또한, 내가 1순위 지원자였다면 학과 내에서 얼마나 강력하게 나를 1순위로 꼽았는지, 그리고 2순위 지원자와 나 사이의 온도 차이가 어느 정도인지를 파악하는 것이 중요합니다. 내가 학과가 정말 원하는 인재라면 잠재적 바게닝 파워가 있습니다. 아웃사이드 오퍼나 리텐션 오퍼가 있다면 명확한 바게닝 칩이 있는 것입니다.

나에게 어느 정도 바게닝 파워가 있는지 파악했다면, 그 정도를 기준으로 카운터 오퍼를 제시하시길 바랍니다. 상대방이 “이 정도면 받아들이겠다”가 아니라, 조금 더 높은 조건, “이 정도면 거절하겠다”고 생각하는 기준으로 제시해야 합니다.

내가 학과로부터 어떤 조건에서, 얼마나 받을 수 있을지는 협상이 끝나기 전까지는 알 수 없습니다. 일단 상대방이 “이건 안 된다”라고 해야 상한선을 파악할 수 있고, “안 된다”라고 하는 근거를 들어야 그 부분에 대해 다시 어떻게 협상해야 할지(혹은 하지 말아야 할지)에 대한 방향을 잡을 수 있습니다. 그래서 저는 협상의 시작은 일단 거절을 받는 것이라고 봅니다.

------------------------------------------------------------------------

마지막으로 유념해야 할 점은, 처음 오퍼를 준 학과에 가시든 아니면 다른 학과로 가시든, 결국 학계를 떠나지 않는 이상 이 분들은 계속 만나게 될 사람들이라는 점입니다. 내가 원하는 조건을 상대방에게 강요하기보다는, 먼저 존중하고 이해하며 서로 윈-윈할 수 있는 방향과 조건을 찾아 나가시길 추천합니다.

좋은 협상은 협상의 과정과 결과를 통해 상호 존중과 신뢰가 더욱 깊어지는 협상입니다.
