---
title: "노력하는 방법"
author:
  name: "김재연"
  url: https://jaeyk.github.io
date: today
---

지금까지 커리어를 쌓아 오면서 저보다 능력 있고 뛰어난 분들과 함께 일할 기회가 많았습니다. 제게 예전보다 조금이라도 발전한 부분이 있다면, 아마도 배울 점이 많은 분들과 함께 일한 덕분이 아닐까 생각합니다.

여러 동료들에게 많은 것을 배웠지만, 특히 노력하는 방식에 대해 크게 깨달은 점들이 있습니다. 이 글에서는 그 주제에 대해 간략하게 정리했습니다.

## 1. 게임의 난이도를 낮추기보다, 본인의 레벨을 높여야 합니다

박사 과정은 누구에게나 힘든 시기입니다. 힘든 시기를 지나면 더 쉬운 길을 찾고 싶은 마음이 드는 것이 자연스러운 일입니다. 그런데 인간은 적응의 동물이기도 합니다.

박사 과정 초반, 저는 UC 버클리 태권도부와 우슈부에서 클럽 활동을 했습니다. 대부분 학부생들이라 저보다 훨씬 젊었고, 그들과 함께 운동하니 힘들면서도 체력이 정말 좋아졌습니다. 지금도 꾸준히 운동을 하지만 그때처럼 고강도로 하지는 않습니다. 나이가 든 것도 있으나 운동량이 줄어들면서 체력도 자연스럽게 예전같지 않게 되었습니다.

연구도 같습니다. 쉽게 가면 약해지고, 어렵게 가면 강해집니다. 의도적으로 스스로에게, 버겁지만 이길 수 있는 '위기'를 만들어야 합니다. 새로운 도전이 될 만한 프로젝트를 찾고, 도전하고, 계속 노력하는 과정을 반복해야 합니다.

위기를 선택하지 않으면 기회도 오지 않습니다.

## 2. 어쩌다 잘 되는 수준이 아니라, '잘 안 되기 어려울 정도'까지 노력해야 합니다

이 기준은 잡톡 글에서 강조했던 내용이기도 하지만, 논문을 쓸 때도 똑같이 적용됩니다. 어쩌다 우연히 잘 되는 수준이 아니라, 어지간해서는 실패하기 어려운 수준까지 자기 자신을 밀어붙여야 합니다. 연구가 마라톤이라면, 그런 점에서 비슷하죠. 그 장거리를 뛰면서 고통이 오지 않을 수 있을까요.

한국 대학에 계신 선생님들의 부탁으로 국내 학생들의 미국 박사 과정 지원서류(SOP)를 어쩌다 검토해 드리곤 합니다. 자기소개서(Personal Statement)와 연구계획서(SOP)를 구분하지 못하는 아주 기본적인 실수도 있지만, 가장 흔한 문제는 "되다 만" 연구계획서가 많다는 점입니다. 애드미션을 받을 때 가장 중요하게 고려되는 이 서류가, 아직 한참 더 발전시키고 다듬어야 하는 경우가 정말 많습니다.

"완성본"은 말 그대로 "완성도"가 있어야 합니다. 실수가 없고, 구멍이 없다는 뜻이죠. 완성도가 나오기 전까지는 수없이 많은 시행착오를 겪을 수밖에 없습니다. 개별 요소가 섬세하게 다듬어져야 합니다. 이 부분들이 논리적으로, 유기적으로, 잘 연결되어 전체가 되어야 합니다. 마지막으로 핵심 메시지가 단순하고, 매력적으로 표현되어야 합니다.

연구계획서든, 논문이든, 잡톡이든 모두 같습니다. 어쩌다 잘 되는 것이 아니라, "잘 안 되기 어려울 정도로" 결과물을 만들기까지는 많은 육체적, 정신적 고통을 견뎌내야 합니다. 무언가를 잘하게 되는 과정은 어느 분야든 지독하게 어렵습니다. 이건 학계에만 국한된 고통도 아닙니다.

## 3. 나를 '찾는 과정'과 나를 '놓는 과정'을 반복해야 합니다

사회과학 연구는 과학적 방법론을 활용하므로 분명 과학적이지만, 동시에 직관적이고 개성적인 요소도 큽니다. 같은 주제를 연구해도 접근법과 문제의식이 각자 다르게 나타나는 이유입니다.

연구자로 성장한다는 것은 특정 분야의 이론과 방법론을 배우고, 기존 연구와 트렌드를 익히는 것만을 의미하지 않습니다. 기계의 학습과 사람의 성장은 다릅니다. 자신의 목소리와 커뮤니티를 찾아가는 과정이기도 합니다.

문제는, 한 번 자리 잡은 내 '목소리'가 곧 내 '틀'이 되어버리면 그것이 성장의 한계가 되기 쉽다는 점입니다. 연구자로서 성장 속도를 유지하려면 일정한 틀이 생긴 순간 다시 그것을 깨고 새로운 동력을 찾아야 한다고 믿습니다. 그 과정에서 후퇴하는 것처럼 느껴질 수도 있습니다. 배울 것이 많아지니까요. 그러나 그렇게 해야만 새로운 기술, 경험, 네트워크가 만들어집니다. 그렇지 않으면 과거의 성취가 오히려 장애물이 됩니다.

나를 찾으려면 학술적 세계(이론과 논의)와 현실 세계(문제에 대한 이해)를 모두 깊이 탐구해야 하고, 그 둘의 간극을 스스로 깊이 고민해야 한다고 생각합니다.

인공지능도 이 문제를 해결하지 못합니다. "없던 길을 만들어 가는 일"은 "스스로" "내면의 깊은 곳"까지 들어가지 않으면 불가능합니다.

한편, 나를 놓기 위해서는 익숙하지 않은 환경에 나를 계속 노출시키는 것이 중요합니다. 이 현상은 이렇게 봐야 한다, 이 문제는 이렇게 접근해야 한다는 식의 '당연함'이 많아지는 것이 저는 위험하다고 생각합니다. 좋은 지도교수는 그래서 바로 이렇게 해라, 저렇게 해라 지시하지 않습니다. 대신에 학생이 어느 정도 헤매더라도 스스로 길을 찾을 때까지 기다려 줍니다. 다만 정말 길을 잃었을 때만 조용히 방향을 잡아줄 뿐입니다.

여가 시간에는 가족과 시간을 보내고, 그 외에는 운동과 독서에 시간을 씁니다. 책을 읽을 때도 제 전공과 직접 관련되지 않은 다양한 분야의 책을 읽습니다. 연구 세미나도 굳이 제 연구분야가 아니어도 참석하고, 다른 분야 연구자들과 교류하는 것도 좋아합니다. 그 과정에서 배우는 것이 정말 많기 때문입니다. 문제를 바라보는 관점이 다양해지면, 적절하게 문제를 정의하고 해결할 수 있는 길이 많아집니다.

::: callout-note
**쉽고, 빠른 길은 없습니다**

위에서 말씀드린 세 가지 원리는 모두 단기적이고 효율적인 노력 방식과는 거리가 있습니다. 운동이든, 독서든, 사업이든, 연구든 저는 단기적·효율적 해결책을 신뢰하지 않습니다.

한 번 잘하는 것(one hit wonder)은 적당한 노력과 우연으로도 가능합니다. 중요한 것은 그 실력을 유지하고 발전시키는 것입니다. 그 롱런하는 길에 들어서는 데에는 쉽고 빠른 방법은 없습니다.
:::
