---
title: "연구 생산성 높이기"
author: 
  name: "김재연"
  url: https://jaeyk.github.io
format:
  html:
    theme: cosmo
    css: styles.css
date: today
---

미국에서 아카데믹 커리어를 추구하는 데 있어서 연구보다 잡을 얻고, 승진을 하는 데 더 중요한 자산은 없습니다. 그래서 다들 연구를 열심히 합니다. 연구에 대한 보상이 명확하니까요. 그러나 자원이 무한정하면 모르겠지만, 돈과 시간에 한계가 있고, 어떤 연구가 잘 될지 모르는 상황에서 연구 생산성을 높이는 것은 쉽지 않은 문제입니다. 이것이 고민이 되는 건 지금이나 대학원 신입생 때나 지금이나 똑같습니다.

연구 생산성에 대한 고민은 정답이 없고, 각자에게 유용한 구체적인 방식은 다를 것이라 믿습니다. 그러나 동시에 함께 고민해 보면 의미 있는 포인트들도 역시 있다고 믿습니다.

대학원 신입생 때부터 지금까지 제가 시행착오를 겪으며 얻은 교훈을 정리해 보았습니다.

## 1. Less is More

저도 그랬고, 많은 대학원생들을 보면 초기에는 시행착오를 겪으며 자기 자신과 필드를 알아가는 단계인지라 이것저것 관심도 많고, 이것저것 많이 합니다. 심지어 연구 주제도 굉장히 큰 경우가 많습니다. 책으로 다뤄야 할 주제를 논문으로 가져오는 경우도 많죠.

지적인 호기심을 채우기 위해 공부를 하는 것이라면 제너럴리스트가 되는 것도 나쁘지 않습니다.

그러나 아카데믹 커리어를 추구하고자 한다면 (제너럴리스트보다는 스페셜리스트, 그것도 (1) **성장 가능성**이 있는 (2) **협소한 분야**에서 명성을 쌓는 스페셜리스트가 되어야 합니다.

학계의 엔트리 포지션(테뉴어 트랙 조교수)을 뽑을 때 한 분야의 제너럴리스트를 뽑는 경우는 없습니다. 이 정도 시야는 학교의 리더십 포지션인 학장(dean)이나 연구부총장(provost), 총장(president)에게는 필요하지만, 쥬니어 패컬티에게는 굳이 있을 필요가 없죠. 그런 시야를 가지고 의사 결정을 내릴 일이 없고, 그런 전문성이 필요한 자리도 아니니까요. 패컬티의 책임은 학교와 학과 내에서 특정 분야의 연구와 교육을 담당하는 것입니다.

따라서 대학원에 들어가서 이것저것 많이 해보겠지만, 어느 시점이 되면 내가 어느 분야에서 연구를 통해 명성을 쌓고, 그 명성을 통해 잡을 얻겠다는 목표를 세워야 합니다. 이 명성을 만드는 가장 직접적이고 명확한 방법은 그 분야에서 인정받는 방식으로 연구 출판을 하는 것입니다.

**왜 내가 택한 분야가 성장 가능성이 있어야 하느냐?**

대학은 기업보다는 오래 생존하는 것이 사실입니다. 그러나 대학도 혁신하지 않으면 명성이 떨어지고, 명성이 떨어져서 교수진과 학생을 잃으면 결국 문을 닫아야 하기 때문입니다. 대학과 유관된 저널도 마찬가지의 인센티브 구조를 가지고 있죠. 트렌드에서 밀리면 안 됩니다. 그래서 대학은 떠오르는 분야의 연구자를 채용하고 싶고, 저널은 떠오르는 분야의 논문을 출판하고 싶습니다.

**이 성장 가능성을 어떻게 판단하느냐?** 

많은 사람들이 대학원 초기에 논문을 많이 접할 당시 유행하는 트렌드를 쫓지만, 학계의 트렌드는 빨리 돌아서 졸업할 때가 되면 잡마켓에 나오면 그 트렌드는 이미 지나가거나 그냥 학계의 상식이 되어버린 경우가 많습니다. 그걸 한다고 더 이상 경쟁 우위가 생기지 않습니다.

트렌드를 무시하지는 않되, 해당 분야의 근본적인 질문을 남보다 더 낫게 해결하는 데 집중하는 것이 현명하다고 봅니다. 학계에서든 민간에서든 트렌드를 선점하는 것은 결코 쉬운 일이 아닙니다.

**왜 협소한 분야를 택해야 하는가?**

어떤 문제를 푸는 것만큼이나 중요한 것은 그 문제를 잘 푸는 것입니다. 어설프게 세 가지 문제를 푸는 것보다, 한 가지 문제라도 정말 깊이 제대로 풀면 더 쉽고 빠르게 그 분야의 명성을 쌓을 수 있습니다.

Less Is More의 원칙은 프로젝트 관리에도 적용됩니다. 여러 페이퍼를 쓰는 것보다 더 중요한 것은 한 페이퍼라도 제대로 된 페이퍼를 쓰는 것입니다. 좋은 저널에 나오더라도 장래 내 명성에 해가 되는 페이퍼가 있다면 독이 됩니다. 결국엔 저널이 아니라 콘텐츠가 중요합니다. 저는 그 이유 때문에 아주 좋은 저널에 수락된 페이퍼였지만, 공저자와 저널 에디터의 양해를 구해 그 페이퍼에서 제 이름을 뺀 적이 있습니다. 논문에 동의할 수 없는 부분이 있었기 때문입니다. 여러 이유로 항상 동시에 여러 프로젝트를 진행하지만, 그 중에서 특정 시기에 가장 많은 시간을 들여 집중하는 페이퍼는 늘 단 한 개입니다.

물론, 처음부터 어디서, 어떻게 좁혀야 할지에 대한 감이 잡히지 않으므로 연구에 있어 시행착오는 피할 수 없습니다. 초기에는 많은 것을 해볼 수밖에 없고, 이것저것을 해봐야 하지만, 탐색하는 기간이 어느 정도 지나면 선택과 집중을 해야 한다는 것을 기억해야 합니다.

새로운 논문 아이디어를 시도할 것인가 말 것인가, 공저라면 그 프로젝트에 내가 얼마나 가담할 것인가를 결정할 때 아래의 질문을 기억해야 합니다. 이 논문이, 이 프로젝트가 내가 쌓으려고 하는 성장 가능성이 있는, 협소한 분야의 전문성을 쌓는 목표와 얼마나 부합하는가? 부합하지 않는다면, (다른 더 잘할 사람들이 학계에 있는 상황에서) 굳이 내가 이 프로젝트에 참여해야 하는가. 그 답이 “No”라면, 거기에 쏟을 시간과 노력을 내 목표에 더 부합하는 논문과 프로젝트에 쏟는 것이 맞다고 봅니다. 

## 2. Don’t Work Too Much and Too Fast

너무 많은 일을 하고 너무 빨리 해내려고 하는 실수”는 연구가 안 될 때와 잘 될 때 공통적으로 나타나는 문제입니다. 연구가 안 될 때는 안 되니까 무리해서 열심히 하고, 연구가 잘 될 때는 또 잘 되니까 무리해서 열심히 합니다.

무리해서 무엇을 하는 것은 단기적으로는 효율적일 수 있으나, 장기적으로는 결코 효과적인 방법이 아닙니다. 심하게 무리하면 크게 쉬어줘야 하고, 그 시기를 놓치면 높은 확률로 번아웃이 오고 아무 것도 하기 싫어집니다. 몸이 아프기도 하고, 그러면 한 주가 쉽게 날아갑니다. 또 오래 강제로 쉬어야 할 수도 있죠.

이건 저도 정말 쉽게 고쳐지지 않는 습관이지만, 한 번에, 하루에 모든 걸 다 하려는 생각을 내려놓아야 합니다. 80%의 에너지로만 연구를 하고, 나머지 20%의 에너지는 내일도 똑같은 에너지 레벨로 일을 할 수 있도록 자기 자신을 관리해야 합니다.

여러 가지를 시도해 보았지만, 그 20%를 충전하는 방식 중 시간 대비 가장 좋은 방식은 제게는 운동과 독서인 것 같습니다.

또한, 인간인 이상 잘 먹고 잘 자야 합니다. 뇌는 에너지를 많이 쓰고, 양질의 영양과 수면을 공급해주지 않으면 뇌가 쓸 에너지가 부족합니다. 다른 방식으로는 그 에너지를 충분히 채워넣을 수가 없습니다.

## 3. Play Your Game

대학원생으로서 학계에 처음 제대로 발을 들이면, 가장 가까이서 보이는 교수, 대학원생들이 역할 모델이 되기 쉽습니다. 저런 식으로 연구를 해야만 저 자리에 갈 수 있을 것처럼 보이죠. 그리고 저 자리가 나에게 가장 맞는 자리처럼 보이죠. 

그러나 실상은 본인이 속한 학과는 전 세계의 많은 학과 중 하나일 뿐입니다. 거기서 경험한 “특수성”을 “보편성”으로 착각하기 쉽고, 거기서 본 “하나의 모델”을 “유일한 모델”로 생각하는 경우도 많습니다.

운이 좋으면 그 모델이 자신의 학자로서의 전문성을 키우고, 그 전문성을 업적과 명성으로 바꾸기 위한 가장 좋은 모델이자 경로가 될 수 있으나, 반드시 그렇게 되리라는 보장은 없습니다. 혹은 한때의 좋은 모델이 졸업할 때가 되면 주변 환경이 바뀌어 더 이상 좋지 않은 모델이 될 수도 있죠. 끝없이 변해야 경쟁력이 유지되는 것은 연구자도 마찬가지입니다.

그래서 논문도 읽고, 논문 쓰는 방법도 중요하지만, 내가 편하면서도 나에게 경쟁력을 줄 수 있는 나만의 스타일을 만드는 것, 자기만의 게임을 하는 것을 중요하게 생각해야 합니다.

예를 들어, 학제간 연구를 하거나 응용 연구를 많이 하는 사람들은 순수 학문을 추구하는 전통 학과에서는 인기가 없을 수 있으나, 패컬티 구성이나 배경이 다른 프로페셔널 스쿨에서는 상대적으로 흥미로운 연구자로 보일 수 있습니다. 아무리 훌륭한 연구자라도 모든 학과가 좋아하는 경우는 없습니다. 각 조직과 집단의 취향이 너무 다르기 때문입니다.

나를 바꾸는 것”보다는 “내 환경을 바꾸는 것”을 추천합니다. 타고난 관심사와 취향을 바꾸는 것은 정말 쉽지 않기 때문입니다. 내가 소속된 조직의 자원을 잘 활용하면서, 내 주변의 예시들이 하나의 모델일 뿐이라는 것을 기억하고, 자신에게 가장 유리한 환경에서 나만의 게임을 하시길 추천합니다.