---
title: "네트워킹 요령"
author: 
  name: "김재연"
  url: https://jaeyk.github.io
format:
  html:
    theme: cosmo
    css: styles.css
date: 2025-05-08
---

미국 학계에서 네트워킹을 잘 하기 위한 조언을 적어 보았습니다. 글의 가독성을 높이기 위해 자문자답 형식을 취했습니다.

## 네트워킹은 반드시 해야 할까요?

반드시 해야 합니다. 본업(=연구)에 지장을 주지 않는 이상, 네트워킹은 많이 할수록 좋습니다. 크게 두 가지 이유에서 네트워킹을 해야 합니다.

첫째, 성공적인 커리어를 쌓기 위해서 열심히 하고 잘 하는 것만으로 부족합니다. 더 많은 사람들, 중요한 사람들(의사결정권자들)이 내가 잘 하는 것을 알고 있어야 합니다. 내가 잘 하는 걸 아는 사람들이 많을 때 나에게 더 많은 기회가 옵니다.

둘째, 이런 평판을 쌓기 위해서 내가 잘 한다고 이야기하는 것보다 다른 사람이 잘 안다고 이야기하는 것이 더 설득력이 있고 효과적입니다.

그럼, 어떻게 이 사람들은 나를 알고 있고, 내가 잘 한다는 걸 알고 있을까요? 나를 만나봤고, 경험했기 때문입니다. 혹은 그렇게 나를 알고 있는 사람을 알고 있기 때문입니다.

## 그렇다면 네트워킹은 어떻게 시작해야 할까요?

정답은 없습니다. 자기한테 편안하고 효과적인 방법을 찾아야 합니다.

그러나 함께 생각해 볼만한 포인트들은 있습니다. 그 포인트들을 아래에 정리하여 보았습니다.

### 1. Define your values (스스로 자신의 가치를 정하라).

이해를 돕기 위해 상황을 하나 가정해 봅시다. 학회는 네트워킹하기에 좋은 곳입니다. 많은 사람들이 모이고 그 사람들 대부분이 새로운 사람을 만나는 것에 대한 기대를 갖고 모이기 때문입니다.

**평소에 관심있는 연구자에게 혹시 잠깐 만나줄 수 있는지 요청을 하려 합니다. 어떻게 요청을 해야 할까요?**

그 연구자에게 이메일을 보내기 전에 그 분의 입장에서 봤을 때 내 포트폴리오의 어떤 부분이 흥미가 있을지 생각해야 합니다.

-   예를 들어, 공동의 연구 주제를 강조할 수 있습니다. 당신이 연구하는 주제 X와 내가 연구하는 주제 Y가 이런 점에서 겹친다. 한 번 만나서 이 공통적인 부분에 대해서 한 번 이야기를 나눠보고 싶다. 이런 내러티브도 좋습니다. 공통점은 호기심을 자극합니다.

-   혹은 나는 당신이 연구하는 주제와 관련있는 주제를 연구하는 사람이고, 너가 쓴 책/페이퍼를 읽었는데 거기에 대해서 내 연구에 어떻게 적용할지 좀더 이야기를 해보고 싶다 이런 식으로 이메일을 보낼 수 있습니다. 상대방한테 관심을 보이면 상대방도 본인에게 관심을 보입니다.

여기서 중요한 것은 상대방이 내게 호기심, 관심을 가질 스스로의 가치를 정하려면 내가 먼저 상대방을 알아야 합니다. 해피아워에 가서 랜덤하게 사람을 만나는 것이 아니라 의도적으로 내가 직접 연락해서 누군가를 만나는 것이면 사실 큰 장점이 있습니다. 내가 만나고자 하는 사람에 대해서 미리 알 수 있는 시간과 기회입니다. 이 기회를 활용하고 만나는 것과 안 하고 만나는 것은 큰 차이입니다. 그래서 적어도 만나려는 분의 책, 페이퍼 하나는 제대로 읽고 만나보길 추천합니다. 만나려는 사람이 무엇을 연구하는 지도 잘 모르는데 연락을 하고, 그 상태에서 대화를 하면 오히려 부정적 인상만 남길 가능성이 큽니다.

### 2. Lower the stakes (상대방의 부담을 낮추라).

대학원생과 포닥도 바쁘지만 교수들은 더 바쁩니다. 책임이 더 크기 때문입니다. 해야 할 일이 많고 돌봐야 할 사람들이 많습니다. 바쁜 사람들에게 만나자고 연락하려면 어떻게 해야 할까요?

이 분들의 상황을 감안하면 학회에서 만나자고 요청하는 이메일은 아무리 길어도 한 문단이 넘어가는 일이 없도록 짧고 명확하게 보내주세요. 그리고 오늘 이메일을 보냈다고 해서, 오늘 회신할 것이라는 기대는 안 하시는 게 좋습니다. 바쁜 사람들은 대체로 회신이 느립니다.

다음은 제가 한 번도 만나지 않았던 바쁜 사람들에게 이메일을 통해 만나자고 요청할 때 쓰는 글의 구조입니다. (a) 나는 이런 이유로 너의 연구를 좋아해 왔다. (b) 나는 이런 사람이고 이런 연구를 한다. (c) 30분 정도의 시간만 줄 수 있다면 이 주제에 대해서 한 번 이야기해 보고 싶고, 너의 사소한 피드백도 큰 도움이 될 것 같다. 이 각 요소에 대해서 한 문장씩 쓰면 총 3문장이면 충분합니다. 읽는 데 5분이면 충분합니다.

그리고 이 분들 스케쥴은 빨리 차니 학회가 있기 적어도 한 달 전에는 연락하시는 것이 좋습니다.

-   회신을 받으면 어떻게 해야 할까요? 상대방이 가능한 시간대 2-3개를 알려주면 내가 최대한 맞추겠다고 하시길 추천합니다. 내가 요청하는 입장에서 내 시간대에 상대방이 맞춰 달라고 하는 것은 무례합니다. 시간대를 알려주면 캘린더 이벤트를 그 사람에게 보내줘서 일정 조정을 도와주세요. 어떻게 하면 그 사람의 삶을 더 쉽게 만들어 줄까를 고민하세요. 여기서 만나기 전에 미리 좋은 인상을 남길 수 있습니다.

-   회신을 못 받으면 어떻게 해야 할까요? 바쁜 사람들이니 t년도 학회에서 만나지 못하거나 혹은 이메일 회신이 없을 수도 있습니다. 자연스러운 일입니다. 이 상황도 기회입니다. 작년에 못 만났으니 올해는 꼭 만나고 싶다라는 말을 t+1년 학회에 가게 되서 그 분에게 다시 연락할 때 언급해 주세요.

    -   그래도 계속 연락이 안 된다면 내게 관심이 없는 것이니 포기하면 됩니다. 모든 사람에게 관심을 받을 필요는 없습니다.

-   만났을 때는 어떻게 해야 할까요?

    -   어떤 질문을 할 것인 지를 생각해 가세요. 먼저, 그 사람의 커리어와 연구에 대해서 묻는 것을 추천합니다. 상대방에게 먼저 관심을 보이고 그 다음에 자신의 질문을 하세요.

    -   대화를 끝났을 때, 혹시 다른 질문이 있으면 팔로우업해도 되는지 물어보세요. 대화의 분위기가 나쁘지 않았다면 거절하는 경우는 거의 본 적이 없습니다. 이렇게 하면 다음에 연락할 때 어색하지 않습니다.

-   만난 후에는 어떻게 해야 할까요?

    -   만난 후에 이메일 감사노트를 보내고 거기에 간결하게 시간 내주셔서 고마웠고 이 부분에 대해 배웠다는 것을 알려주세요. 그래야 상대방도 시간을 헛되이 쓰지 않았다는 것을 알게 됩니다.

    -   상대방과 대화를 통해서 배운 내용이 있고, 그 내용을 적용해서 커리어와 연구가 개선되었다면 나중에 꼭 팔로우업해주세요. 이렇게 해서 한 번 만난 관계가 동료 관계로 발전합니다.

여기서 키 포인트는 상대방이 부담을 갖지 않게 작게 시작하고, 관심과 배려를 통해서 단계적으로 상호 신뢰를 쌓아가는 것입니다.

## 3. Be a service to others (먼저 주는 사람이 되라).

**어디에서 서로의 커리어에 도움을 줄 수 있는 사람들을 만날 수 있을까요?** 

꼭 학회에 가지 않더라도 그런 네트워킹을 형성할 수 있는 기회는 사실 많습니다. 예를 들어, 많은 학과들이 대학원생을 워크숍 코어네이터로 활용합니다. 이 기회를 통해 다른 학교에 있는 실력있는 학자들을 만나고 그 분들과 관계를 형성할 수 있습니다. 자기가 소속된 학과에서 외부 인사를 초청해 진행하는 워크숍이 없거나 활발하지 않다면 소셜 미디어를 이용하는 것도 좋은 방법입니다. 혹은 관심있는 분에게 콜드 이메일을 보낸 후, 짧은 줌이나 전화 대화를 요청할 수도 있습니다. 물론, 상대방에게 줄 수 있는 가치가 내게 적을 때, 상대방이 써야 할 시간과 노력이 클수록 이 만남이 성사될 가능성은 낮아집니다.

그러나 누군가를 만날 기회만으로 그것이 좋은 네트워킹 기회가 되지는 않습니다. 특별한 네트워킹 기회는 다른 사람에게 특별한 서비스를 할 때, 그 사람에게 특별한 가치를 줄 때 찾아 옵니다. 

제 자신의 예를 들어 보겠습니다. 저 같은 경우는 UC 버클리 정치학 박사 과정 재학 중에 2019년에 프린스턴에서 Summer Institute in Computational Social Science(전산사회과학 여름학교)란 프로그램에 2주간 참여했습니다. 이 Summer Institute의 목표는 전산사회과학의 저변 확장입니다. 따라서 이 Summer Institue는 프린스턴과 듀크가 메인 로케이션이지만 그외에 미국 내외의 다양한 파트너 로케이션을 만드는 것을 목표로 합니다. 디렉터들로부터 그 아이디어를 듣고 자원하여 저는 그 다음 해에 UC 버클리와 스탠포드가 공동 주최하는 Summer Institute in Computational Social Science in the SF-Bay Area를 조직했습니다. 이 경험을 통해 다양한 분야의 많은 패컬티, 포닥, 대학원생들을 만났습니다. 그때 만났던 사람들 중에 상당수가 지금은 제 친구, 동료, 공저자입니다. 이 분들이 서로 교류할 수 있는 장을 만들어 준 오거나이저였기 때문에 이들의 관계의 중심이 될 수 있습니다. Bay Area 행사를 개최할 때 행사의 목표는 전산사회과학자와 지역 단체들간의 연구 협력 프로젝트를 진행하는 것이었습니다. 이를 위해 만난 단체 중 하나가 미국의 대표적 시빅 테크 단체인 Code for America였습니다. 그냥 학생이었다면 이 단체를 만나고 그곳에서 일하는 바쁜 사람들을 만나기 어려웠겠지만 이 단체도 관심을 가질 만한 행사를 조직하고 있었기 때문에 만날 기회가 주어졌습니다. 이 비영리 회사에서는 나중에 풀타임 데이터 과학자로 일하기도 했습니다. 

꼭 이런 행사를 조직할 필요는 없습니다. 키 포인트는 먼저 주는 사람에게 더 많은 기회가 온다는 것입니다. 

그런 점에서 동료, 친구들에게 도움을 주는 것도 네트워킹입니다. 그래서 다른 것은 몰라도 동료와 친구들이 요청한 프랙틱스 잡 톡을 안 가본 적은 거의 없습니다.

먼저 주는 것을 추천합니다. 이것이 더 넓고 깊은 관계를 만드는 방법이기 때문입니다. 

## 4. Build your board of advisors (너만의 자문단을 만들라). 

**네트워킹은 언제부터 시작해야 할까요?**

이미 시작하셨습니다. 대학원에 입학하여 수업을 들으면서 다른 학생들과 관계를 맺는 것, 네트워킹입니다. 지도교수를 정하기 위해 교수를 컨택하고 그분들과 1:1을 하고, 그분들의 논문 지도를 받는다면 그것도 네트워킹입니다. 학회를 가서 발표를 하고 사람을 만난다면, 역시 네트워킹입니다. 

다만, 이 네트워킹을 전략적으로 의식적으로 하는 사람과 그렇지 않은 사람이 있을 뿐입니다. 개인적으로, 전략적으로 의식적으로 네트워킹을 하는 것을 추천합니다. 그렇게 하는 것이 스트레스는 줄고 효과는 늘고, 서로에게 도움이 됩니다. 관계를 맺은 사람들에게 서로 도움이 되는 네트워킹이 좋은 네트워킹입니다. 

박사 논문을 쓴다면 박사 논문 커미티가 있습니다. 박사 논문이란 큰 프로젝트를 하기 위해서 주변의 도움이 필요하기 때문이죠. 

그러나 이 공식적 자문단 외에도 사실 아카데믹 커리어를 위해 여러 자문단이 필요합니다. 잡 마켓에 나가려 하는 데 지도교수님들이 모두 졸업하신 지 오래된 분들이라면 현재 잡마켓 상황과 트렌드를 잘 모를 수 있습니다. 이럴 때는 최근 잡 마켓에 나가본 사람들을 위주로 한 비공식 커미티가 있어야 합니다. 이 분들의 자문을 받아야 합니다. 테뉴어 트랙에 들어가서 테뉴어를 받기 위한 준비를 할 때도 마찬가지겠죠. 학계에 있다가 업계로 넘어가려 하거나, 업계에 있다가 학계로 다시 돌아갈 때도 역시 마찬가지입니다. 커리어의 과정에 따라서, 방향에 따라서 계속 새로운 자문단이 필요합니다.

네트워킹을 하면서 만든 관계들 중에 어떤 관계는 친구가 되고, 어떤 관계는 동료가 되고, 어떤 관계는 공저자가 되고, 어떤 관계는 멘토가 되고, 어떤 관계는 멘티가 되고, 어떤 관계는 비공식 자문단의 일부가 됩니다. 

내게 도움이 되는 네트워킹을 하기 원한다면 나도 상대방에게 그런 사람,그런 친구, 동료, 공저자, 멘토, 멘티, 비공식 자문단의 일부가 되어주세요. 

서로 도와주는 관계가 건강하고, 그런 관계가 오래 갑니다.    

## 5. Networking is a skill (네트워킹도 기술이다). 

**전 관계에 서툰 사람입니다. 네트워킹을 저 같은 사람도 잘할 수 있을까요?**

성격 유형을 따진다면 전 사람 만나는 것을 좋아하지 않습니다. 학부는 한국에서 나왔는데, 신입생 오리엔테이션을 제외하고 학교와 학과 행사에 거의 가본 적이 없습니다. 휴식을 취할 때는 야외에서 “혼자” 운동을 하거나 집에서 “혼자” 음악을 듣고 책을 읽고 요리를 하는 것을 선호합니다. 기본적으로 저녘에 사람을 만나는 것을 좋아하지 않습니다. 저녘은 나만의 시간이고, 그때는 혼자 쉬는 것을 좋아하기 때문입니다. 

미국 학계에서 네트워킹을 고민하고 실행하게 된 것은 내 커리어를 위해 이것이 선택이 아니라 필수라는 것을 깨달았기 때문입니다. 사람을 만나야 기회가 옵니다. 노력과 실력에 평판이 더해졌을 때 기회가 주어집니다. 상을 받기 위한 가장 쉬운 방법은 이전에 상을 받는 것입니다. 

소수의 사람들을 제외하면 태어날 때부터 네트워킹이 쉬운 사람들은 없습니다. 대다수가 네트워킹을 잘 하기 위해 많은 것들을 새로 배워야 하고, 많은 시행착오를 겪어야 하기 때문입니다. 나아가, 미국에서 학부를 나오지 않은 한인 대학원생들이 미국 학계에서 네트워킹을 하려면 추가적으로 겪어야 할 언어적, 문화적 장벽이 있을 것입니다. 

그러나 네트워킹도 (사회적) 기술입니다. 하면 할수록 더 잘 하게 됩니다. 나아가, 네트워킹을 위해 초기에 의도적 투자가 필요한 것은 사실입니다. 그러나 어느 정도 관계 형성이 되면 내가 별도의 노력을 하지 않더라도 평판이 전해지고 사람이 또다른 사람을 소개시켜 주기 때문에 자연스럽게 네트워킹이 됩니다. 

네트워킹을 할 때 초반에 부정적 경험을 할 수도 있으나 거기에 너무 집중하지 마시고 롱게임을 하시길 추천합니다. 

네트워킹은 누구나 해야 하는 일이고 전략적으로 연습하면 누구나 잘 할 수 있는 기술입니다.