---
title: "발제와 토론의 기술"
author: 
  name: "김재연"
  url: https://jaeyk.github.io
format:
  html:
    theme: cosmo
    css: styles.css
date: today
---

미국에서 박사를 마치고 여기서 활동하는 연구자로서, 어쩌다 한국 대학의 학부생과 대학원생들이 발제와 토론을 하는 모습을 지켜볼 때 느꼈던 아쉬운 점을 적어 봅니다.

한국에는 재능 있고 열심히 하시는 분들이 정말 많으신데, 이 부분들을 고려하시면 나중에 미국으로 대학원 유학을 오시거나, 아니면 여기 학회에서 발제와 토론을 하실 때 더 잘 하실 수 있으리라 믿습니다.

여기서 제가 말하는 발제와 토론은 지정된 논문에 대한 발제와 토론을 의미합니다.

## 1. 논문 정리는 2, 내 생각은 8

제가 느낀 가장 아쉬운 점은, 많은 한국 학생들의 발제와 토론이 읽은 논문에 대한 정리에서 그친다는 것입니다. 본인의 발제와 토론이라면, 자신의 생각이 주가 되어야 하지 않을까요?

발제와 토론에서는 20%만 논문 정리에, 80%는 본인의 생각을 비판적으로 주장하고 논리적으로 전개하는 데 집중하시길 권합니다. 미국 사회과학 강의에서는 방법론을 제외하면 보통 논문을 읽고 think piece를 학기 중에 여러 개 쓰며, 나중에 term paper를 쓰는 것이 과제입니다. 여기서도 think piece를 잘 쓰려면 읽은 논문 정리는 짧게 하고, 나머지 지면은 자기 생각을 비판적이고 논리적으로 잘 표현하는 데 집중해야 합니다. 그래야 좋은 평가를 받습니다. 논문 정리가 2: 내 생각이 8이라는 레시피가, 수업에서 교수들이 학생에게 기대하는 바이고, 학회에서 참가자들이 토론자에게 기대하는 바입니다.

## 2. Better, not perfect

지엽적인 코멘트는 지양하는 것이 좋습니다. 어차피 코멘트의 개수가 다섯 손가락을 넘어가면 다 기억하는 사람은 거의 없고, 좋은 인상을 남기기도 어렵습니다. (비슷한 관점에서, 청중으로서 질문할 때도 웬만하면 한 개, 많아야 두 개만 질문하시는 것이 좋습니다. 그리고 질문은 물음표로 끝나야 한다는 점, 아시죠?)

공식 발제자나 토론자로서 내 생각을 적고 전할 때도 핵심 아이디어 2\~3가지만 정리하여 그것만 잘 표현하는 것이 좋습니다. 어떤 아이디어가 핵심인가라고 묻는다면, “논문의 주장이 더 탄탄해지고 근거가 더 충실해지겠다”는 생각을 들게 해주는 질문과 생각이 핵심입니다.

달리 말하면, **better not perfect**가 핵심입니다. 이런 생각도 해볼 수 있고, 저런 생각도 해볼 수 있겠지만, 그 모든 것을 다 적용해야 더 좋은 논문이 되는 걸까요? 전혀 그렇지 않습니다. 그럴 시간과 자원이 있는 연구자도 없고, 그렇게 해야 꼭 좋은 논문이 나오는 것도 아닙니다. 좋은 논문은 완벽한 논문이 아니며, 사실 완벽한 논문은 존재하지 않습니다.

발제자와 토론자로서의 역할은 주어진 논문을 더 낫게 만드는 방법을 생각하고 제안하는 것이지, 완벽하게 만드는 것이 아닙니다. 이 원칙은 내 논문이 아니라 다른 사람의 논문을 발제하거나 토론할 때는 더욱 중요합니다.

## 3. 많이 읽고, 더 읽으라

학생들이 많이 읽는 것을 힘들어하므로 교수 입장에서는 학생들에게 리딩 양을 늘리라고 하기가 쉽지는 않습니다. 교수들은 학생들이 다른 수업도 듣고, 프로젝트도 수행하며, 개인 생활도 있다는 것을 알고 있습니다.

그러나 강의에서 지정된 리딩이 내가 해당 분야의 연구자가 되기에 충분한 리딩이라고 생각하면 큰 오산입니다. 보통 강의에서 지정된 리딩은 최소한 "이 정도는 읽어야 이 분야에 조금이나마 감이 온다"는 목표를 위한 과제라고 생각하면 맞습니다. 그 분야를 정말 깊이 이해하고 싶고, 그 영역에서 정말 잘하고 싶다면 훨씬 많이 읽어야 하고, 꾸준히 읽어야 합니다. 이는 학부, 대학원, 그 이후에도 마찬가지입니다.

발제와 토론을 잘 하는 가장 근본적인 방법은 많이 읽고, 더 읽는 것입니다. 맥락을 잘 모르니 논문을 읽어도 그 논문의 특별한 공헌이나 혁신이 어디에 있는지 이해하기 어려운 경우가 많습니다. 또, 맥락을 모르니 기존의 논문을 더 좋은 논문으로 만들 수 있는 관점을 찾기가 어렵습니다. 해결책은, 결국 많이 읽는 것입니다.

많이 읽고, 더 읽는다고 해서 논문을 비판적으로 읽고 해석하는 문제가 자동으로 해결되지는 않으나, 그러나 읽지 않고서는 그 길이 보이지 않습니다.

그리고 많이 읽다 보면 읽는 것이 쉬워집니다. 나무만 보고 숲을 보지 못할 때는 길을 헤매기 쉽지만, 일단 숲을 보기 시작하면 왜 저 나무가 저기에 저렇게 있어야 했는지가 서서히 보이기 시작합니다.
